# Generated by Django 5.0.7 on 2026-06-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500, verbose_name='Event Image Path or URL')),
                ('caption_en', models.CharField(max_length=255, verbose_name='Caption (English)')),
                ('caption_ta', models.CharField(max_length=255, verbose_name='Caption (Tamil)')),
                ('col_span', models.IntegerField(default=2, verbose_name='Layout Column Span')),
                ('row_span', models.IntegerField(default=1, verbose_name='Layout Row Span')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('area', models.CharField(max_length=255, verbose_name='Area / Ward')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volunteer Request',
                'verbose_name_plural': 'Volunteer Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ta', models.CharField(max_length=255, verbose_name='Title (Tamil)')),
                ('text_en', models.TextField(verbose_name='Text (English)')),
                ('text_ta', models.TextField(verbose_name='Text (Tamil)')),
                ('tag_en', models.CharField(default='Organisation', max_length=100, verbose_name='Tag (English)')),
                ('tag_ta', models.CharField(default='அமைப்பு', max_length=100, verbose_name='Tag (Tamil)')),
                ('img', models.CharField(default='/assets/branding/flag.png', max_length=500, verbose_name='Image Path or URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Update',
                'verbose_name_plural': 'News Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
