# Generated by Django 5.0.7 on 2026-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Petitioner Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read by Admin')),
            ],
            options={
                'verbose_name': 'Petition',
                'verbose_name_plural': 'Petitions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
