# Generated by Django 5.0.7 on 2026-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_petition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Membership Application', 'verbose_name_plural': 'Membership Applications'},
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='address',
            field=models.TextField(blank=True, verbose_name='Residential Address'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='interests',
            field=models.CharField(blank=True, max_length=500, verbose_name='Areas of Interest'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Occupation / Profession'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='photo_data',
            field=models.TextField(blank=True, null=True, verbose_name='Profile Photo (Base64)'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='photo_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Photo Filename'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status'),
        ),
    ]
