# Generated by Django 5.0.7 on 2026-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_joinrequest_options_joinrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Solved', 'Solved')], default='Pending', max_length=20, verbose_name='Petition Status'),
        ),
    ]
