# Generated by Django 5.0.7 on 2026-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_petition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Area / Ward'),
        ),
        migrations.AddField(
            model_name='petition',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='petition',
            name='photo_data',
            field=models.TextField(blank=True, null=True, verbose_name='Petition Photo (Base64)'),
        ),
        migrations.AddField(
            model_name='petition',
            name='photo_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Photo Filename'),
        ),
    ]
