# Generated by Django 5.0.7 on 2026-06-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='problem_type',
            field=models.CharField(default='Others', max_length=100, verbose_name='Problem Category'),
        ),
    ]
