# Generated by Django 5.0.7 on 2026-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_petition_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='problem_type',
            field=models.CharField(choices=[('Water', 'Water'), ('Road', 'Road'), ('Electricity', 'Electricity'), ('Garbage', 'Garbage'), ('Personal', 'Personal'), ('Others', 'Others')], default='Others', max_length=50, verbose_name='Problem Type'),
        ),
    ]
