# Generated by Django 5.0.7 on 2026-06-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_petition_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='src',
            field=models.TextField(verbose_name='Event Image Path or URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.TextField(default='/assets/branding/flag.png', verbose_name='Image Path or URL'),
        ),
    ]
