# Generated by Django 5.0.7 on 2026-06-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_src_alter_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='address',
            field=models.TextField(default='', verbose_name='Residential Address'),
        ),
        migrations.AddField(
            model_name='petition',
            name='google_map_location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Map Location'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assembly'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='problem_type',
            field=models.CharField(choices=[('Water', 'Water'), ('Road', 'Road'), ('Electricity', 'Electricity'), ('Garbage', 'Garbage'), ('StreetLight', 'Street Light'), ('Sewage', 'Drainage & Sewage'), ('PublicHealth', 'Public Health & Sanitation'), ('Transport', 'Bus & Transport'), ('RationShop', 'Ration Shop'), ('Safety', 'Safety & Policing'), ('Environment', 'Environment & Pollution'), ('Personal', 'Personal'), ('Others', 'Others')], default='Others', max_length=50, verbose_name='Problem Type'),
        ),
    ]
