# Generated by Django 5.0.7 on 2026-06-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_petition_address_petition_google_map_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='problem_type',
            field=models.CharField(choices=[('Water', 'Drinking Water / குடிநீர்'), ('Road', 'Road Facilities / சாலை வசதி'), ('StreetLight', 'Street Light / தெருவிளக்கு'), ('Sewage', 'Drainage / Sewage Canal / கழிவுநீர் கால்வாய்'), ('Garbage', 'Sanitation / Garbage Removal / தூய்மை / குப்பை அகற்றுதல்'), ('PublicToilet', 'Public Toilet / பொது கழிப்பறை'), ('Electricity', 'Electricity / மின்சாரம்'), ('Hospital', 'Government Hospital / அரசு மருத்துவமனை'), ('Education', 'School / Education / பள்ளி / கல்வி'), ('Transport', 'Bus Facilities / பேருந்து வசதி'), ('Pension', 'Old Age Pension / முதியோர் உதவித்தொகை'), ('DifferentlyAbled', 'Differently Abled Welfare / மாற்றுத்திறனாளி நலன்'), ('RationShop', 'Ration Shop / ரேஷன் கடை'), ('Revenue', 'Revenue Department / வருவாய் துறை'), ('TASMAC', 'TASMAC Related Issue / டாஸ்மாக் தொடர்பான பிரச்சனை'), ('Safety', "Women's Safety / பெண்கள் பாதுகாப்பு"), ('Others', 'Other Issues / பிற பிரச்சனை')], default='Others', max_length=50, verbose_name='Problem Type'),
        ),
    ]
