# Generated by Django 5.0.7 on 2026-06-20 08:50

from django.db import migrations, models


def seed_branch_leaders(apps, schema_editor):
    BranchLeader = apps.get_model('api', 'BranchLeader')
    
    # 1. Create the MLA Candidate (Thirumalai)
    BranchLeader.objects.create(
        name="திருமலை",
        branch="மடத்துக்குளம் சட்டமன்ற தொகுதி",
        phone="9876543210",  # Placeholder phone
        email="thirumalai@gmail.com",  # Placeholder email
        is_mla_candidate=True,
        order=0
    )
    
    # 2. Create the branch leaders
    leaders_data = [
        ("மோதி முகமது", "உடுமலை ஒன்றியம்", "9659646272"),
        ("யுவராஜ்", "உடுமலை தெற்கு ஒன்றியம்", "9965249864"),
        ("மனோஜ் குமார்", "மடத்துக்குளம் மேற்கு ஒன்றியம்", "9965227845"),
        ("பாபு", "மடத்துக்குளம் வடக்கு ஒன்றியம்", "6380743383"),
        ("செல்வகணேஷ்", "மடத்துக்குளம் மத்திய ஒன்றியம்", "9080276508"),
        ("சரவணன்", "தளி பேரூராட்சி", "6383618026"),
        ("ஜெபஸ்டின் சூர்யா", "மடத்துக்குளம் பேரூராட்சி", "6369204265"),
        ("ஆதவன்", "கணியூர் பேரூராட்சி", "8220194151"),
        ("சங்கரமநல்லூர் பேரூராட்சி - ஐயப்பன்", "சங்கரமநல்லூர் பேரூராட்சி", "9940903162"),  # Note: user wrote "சங்கரமநல்லூர் பேரூராட்சி - ஐயப்பன் 9940903162" -> name "ஐயப்பன்"
        ("முனிஷ்", "குமரலிங்கம் பேரூராட்சி", "9698622816")
    ]
    
    # Wait, let's clean up the "சங்கரமநல்லூர் பேரூராட்சி - ஐயப்பன்" item:
    # User listed: "சங்கரமநல்லூர் பேரூராட்சி - ஐயப்பன் 9940903162" -> Name "ஐயப்பன்", Branch "சங்கரமநல்லூர் பேரூராட்சி"
    # Let's write the names and branches properly:
    
    # Let's define the correct list:
    leaders_data_clean = [
        ("மோதி முகமது", "உடுமலை ஒன்றியம்", "9659646272"),
        ("யுவராஜ்", "உடுமலை தெற்கு ஒன்றியம்", "9965249864"),
        ("மனோஜ் குமார்", "மடத்துக்குளம் மேற்கு ஒன்றியம்", "9965227845"),
        ("பாபு", "மடத்துக்குளம் வடக்கு ஒன்றியம்", "6380743383"),
        ("செல்வகணேஷ்", "மடத்துக்குளம் மத்திய ஒன்றியம்", "9080276508"),
        ("சரவணன்", "தளி பேரூராட்சி", "6383618026"),
        ("ஜெபஸ்டின் சூர்யா", "மடத்துக்குளம் பேரூராட்சி", "6369204265"),
        ("ஆதவன்", "கணியூர் பேரூராட்சி", "8220194151"),
        ("ஐயப்பன்", "சங்கரமநல்லூர் பேரூராட்சி", "9940903162"),
        ("முனிஷ்", "குமரலிங்கம் பேரூராட்சி", "9698622816")
    ]
    
    for name, branch, phone in leaders_data_clean:
        BranchLeader.objects.create(
            name=name,
            branch=branch,
            phone=phone,
            is_mla_candidate=False,
            order=1
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_petition_problem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name / பெயர்')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch / ஒன்றியம் / பேரூராட்சி')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number / தொலைபேசி எண்')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address / மின்னஞ்சல் முகவரி')),
                ('photo_data', models.TextField(blank=True, null=True, verbose_name='Photo (Base64)')),
                ('photo_name', models.CharField(blank=True, max_length=255, verbose_name='Photo Filename')),
                ('is_mla_candidate', models.BooleanField(default=False, verbose_name='Is MLA Candidate / சட்டமன்ற வேட்பாளர்')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Branch Leader / Candidate',
                'verbose_name_plural': 'Branch Leaders & Candidates',
                'ordering': ['-is_mla_candidate', 'order', 'id'],
            },
        ),
        migrations.RunPython(seed_branch_leaders),
    ]
