# Generated by Django 5.0.7 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_branchleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchleader',
            name='constituency',
            field=models.CharField(default='மடத்துக்குளம் சட்டமன்ற தொகுதி', max_length=255, verbose_name='Constituency / சட்டமன்ற தொகுதி'),
        ),
    ]
