# Generated by Django 5.0.7 on 2026-06-20 09:02

from django.db import migrations


def seed_udumalai_leaders(apps, schema_editor):
    BranchLeader = apps.get_model('api', 'BranchLeader')
    
    leaders_data = [
        ("கார்த்திகேயன்", "ஜமீன்ஊத்துக்குளி பேரூராட்சி", "9629898043"),
        ("அசாரூதீன்", "சூளேஸ்வரன்பட்டி பேரூராட்சி", "9524477347"),
        ("கார்த்திக்", "சமத்தூர் பேரூராட்சி", "8838648536"),
        ("மனோஜ் குமார்", "பொள்ளாச்சி தெற்கு ஒன்றியம்", "9629921226"),
        ("காஜா மைதீன்", "உடுமலை கிழக்கு ஒன்றியம்", "9942061130"),
        ("மோகன்", "உடுமலை வடமேற்கு ஒன்றியம்", "6381971164"),
        ("சரஸ்வதி", "குடிமங்கலம் கிழக்கு ஒன்றியம்", "9655886636"),
        ("ஜெயப்பிரகாஷ்", "குடிமங்கலம் வடக்கு ஒன்றியம்", "8012102032"),
        ("காந்தி", "குடிமங்கலம் மேற்கு ஒன்றியம்", "9750727107")
    ]
    
    for name, branch, phone in leaders_data:
        BranchLeader.objects.create(
            name=name,
            constituency="உடுமலை சட்டமன்ற தொகுதி",
            branch=branch,
            phone=phone,
            is_mla_candidate=False,
            order=1
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_branchleader_constituency'),
    ]

    operations = [
        migrations.RunPython(seed_udumalai_leaders),
    ]
