# Generated by Django 5.0.7 on 2026-06-20 09:12

from django.db import migrations


def add_udumalpet_mla(apps, schema_editor):
    BranchLeader = apps.get_model('api', 'BranchLeader')
    
    # Create the MLA Candidate for Udumalpet (Sanker)
    BranchLeader.objects.create(
        name="சங்கர்",
        constituency="உடுமலை சட்டமன்ற தொகுதி",
        branch="உடுமலை சட்டமன்ற தொகுதி",
        phone="9876543210",  # Placeholder, editable in IT Wing Panel
        email="sanker@gmail.com",  # Placeholder, editable in IT Wing Panel
        is_mla_candidate=True,
        order=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20260620_0902'),
    ]

    operations = [
        migrations.RunPython(add_udumalpet_mla),
    ]
